rm -Rf phasereditor/org.json/target
rm -Rf phasereditor/phasereditor.animation.ui/target
rm -Rf phasereditor/phasereditor.animation.ui.editor/target
rm -Rf phasereditor/phasereditor.assetexplorer.ui/target
rm -Rf phasereditor/phasereditor.assetpack.core/target
rm -Rf phasereditor/phasereditor.assetpack.ui/target
rm -Rf phasereditor/phasereditor.assetpack.ui.editor/target
rm -Rf phasereditor/phasereditor.atlas.core/target
rm -Rf phasereditor/phasereditor.atlas.ui/target
rm -Rf phasereditor/phasereditor.atlas.ui.editor/target
rm -Rf phasereditor/phasereditor.audio.core/target
rm -Rf phasereditor/phasereditor.audiosprite.core/target
rm -Rf phasereditor/phasereditor.audiosprite.ui/target
rm -Rf phasereditor/phasereditor.audiosprite.ui.editor/target
rm -Rf phasereditor/phasereditor.audio.ui/target
rm -Rf phasereditor/phasereditor.bmpfont.core/target
rm -Rf phasereditor/phasereditor.bmpfont.ui/target
rm -Rf phasereditor/phasereditor.chains.core/target
rm -Rf phasereditor/phasereditor.chains.ui/target
rm -Rf phasereditor/phasereditor.help/target
rm -Rf phasereditor/phasereditor.help.phaser/target
rm -Rf phasereditor/phasereditor.ide/target
rm -Rf phasereditor/phasereditor.ide.features/target
rm -Rf phasereditor/phasereditor.inspect.core/target
rm -Rf phasereditor/phasereditor.inspect.core.tests/target
rm -Rf phasereditor/phasereditor.inspect.ui/target
rm -Rf phasereditor/phasereditor.libgdx/target
rm -Rf phasereditor/phasereditor.lic/target
rm -Rf phasereditor/phasereditor.optipng.core/target
rm -Rf phasereditor/phasereditor.optipng.ui/target
rm -Rf phasereditor/phasereditor.platform/target
rm -Rf phasereditor/phasereditor.project.core/target
rm -Rf phasereditor/phasereditor.project.ui/target
rm -Rf phasereditor/phasereditor.resources.executables/target
rm -Rf phasereditor/phasereditor.resources.executables.linux/target
rm -Rf phasereditor/phasereditor.resources.executables.macos/target
rm -Rf phasereditor/phasereditor.resources.executables.win32/target
rm -Rf phasereditor/phasereditor.resources.phaser.code/target
rm -Rf phasereditor/phasereditor.resources.phaser.examples/target
rm -Rf phasereditor/phasereditor.resources.phaser.examples.assets.audio/target
rm -Rf phasereditor/phasereditor.resources.phaser.metadata/target
rm -Rf phasereditor/phasereditor.resources.templates/target
rm -Rf phasereditor/phasereditor.scene.core/target
rm -Rf phasereditor/phasereditor.scene.ui/target
rm -Rf phasereditor/phasereditor.scene.ui.editor/target
rm -Rf phasereditor/phasereditor.spritedemo.core/target
rm -Rf phasereditor/phasereditor.text/target
rm -Rf phasereditor/phasereditor.text.ui/target
rm -Rf phasereditor/phasereditor.ui/target
rm -Rf phasereditor/phasereditor.webrun.core/target
rm -Rf phasereditor/phasereditor.webrun.ui/target
rm -Rf phasereditor/phasereditor.wildwebdeveloper/target
rm -Rf phasereditor/phasereditor.wildwebdeveloper.core/target