
// -- user code here --

/* --- start generated code --- */

// Generated by  1.4.3 (Phaser v2.6.2)


/**
 * Level.
 */
class Level extends Phaser.State {
	
	constructor() {
		
		super();
		
	}
	
	init() {
		
		this.stage.backgroundColor = '#ff8000';
		
	}
	
	preload () {
		
	}
	
	create() {
		this.add.text(300, 290, 'You are playing now!', {"font":"bold 20px Arial"});
		
		
		
		
	}
	
	
	/* state-methods-begin */
	// -- user code here --
	/* state-methods-end */
	
}
/* --- end generated code --- */
// -- user code here --
