// The MIT License (MIT)
//
// Copyright (c) 2015, 2016 Arian Fornaris
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to permit
// persons to whom the Software is furnished to do so, subject to the
// following conditions: The above copyright notice and this permission
// notice shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
// NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
// USE OR OTHER DEALINGS IN THE SOFTWARE.
package phasereditor.canvas.core;

import static java.lang.String.format;

import phasereditor.assetpack.core.IAssetFrameModel;
import phasereditor.assetpack.core.IAssetKey;
import phasereditor.assetpack.core.ImageAssetModel;
import phasereditor.assetpack.core.SpritesheetAssetModel;
import phasereditor.lic.LicCore;

/**
 * @author arian
 *
 */
public class JSCodeGenerator implements ICodeGenerator {

	public static final String END_GENERATED_CODE = "// --- end generated code ---";

	@Override
	public String generate(WorldModel model) {
		StringBuilder sb = new StringBuilder();
		sb.append("// Generated by " + LicCore.PRODUCT_NAME + "\n\n");
		String classname = model.getClassName();
		sb.append("function " + classname + "(game, parent) {\n");
		sb.append(tabs(1) + "Phaser.Group.call(this, game, parent);\n\n");

		{
			int i = 0;
			int last = model.getChildren().size() - 1;
			for (BaseObjectModel child : model.getChildren()) {
				generate(1, sb, child, "this");
				if (i < last) {
					sb.append("\n");
				}
				i++;
			}
		}

		sb.append("\n");
		sb.append(tabs(1) + "if (this.userInit) {\n");
		sb.append(tabs(2) + "this.userInit();\n");
		sb.append(tabs(1) + "}\n");

		sb.append("}\n");

		sb.append(classname + ".prototype = Object.create(Phaser.Group.prototype);\n");
		sb.append(classname + ".prototype.constructor = Phaser.Group;\n");
		sb.append("\n");
		sb.append(END_GENERATED_CODE);
		return sb.toString();
	}

	private static void generate(int indent, StringBuilder sb, BaseObjectModel model, String parVar) {
		if (!model.isEditorGenerate()) {
			return;
		}

		if (model instanceof GroupModel) {
			generateGroup(indent, sb, (GroupModel) model, parVar);
		} else if (model instanceof BaseSpriteModel) {
			generateSprite(indent, sb, (BaseSpriteModel) model, parVar);
		}
	}

	private static void generateSprite(int indent, StringBuilder sb, BaseSpriteModel model, String parVar) {
		sb.append(tabs(indent));
		String varname = model.getEditorName();
		sb.append(parVar + "." + varname + " = game.add.");
		if (model instanceof ImageSpriteModel) {
			ImageSpriteModel image = (ImageSpriteModel) model;
			sb.append("sprite(" + // sprite
					round(image.getX())// x
					+ ", " + round(image.getY()) // y
					+ ", '" + image.getAssetKey().getKey() + "'" // key
					+ ", null" // frame
					+ ", " + parVar // group
					+ ")");
		} else if (model instanceof SpritesheetSpriteModel || model instanceof AtlasSpriteModel) {
			AssetSpriteModel<?> sprite = (AssetSpriteModel<?>) model;
			IAssetKey frame = sprite.getAssetKey();
			String frameValue = frame instanceof SpritesheetAssetModel.FrameModel
					? Integer.toString(((SpritesheetAssetModel.FrameModel) frame).getIndex())
					: "'" + frame.getKey() + "'";
			sb.append("sprite(" + // sprite
					round(sprite.getX())// x
					+ ", " + round(sprite.getY()) // y
					+ ", '" + sprite.getAssetKey().getAsset().getKey() + "'" // key
					+ ", " + frameValue // frame
					+ ", " + parVar // group
					+ ")");
		} else if (model instanceof ButtonSpriteModel) {
			ButtonSpriteModel button = (ButtonSpriteModel) model;
			String outFrameKey;
			if (button.getAssetKey().getAsset() instanceof ImageAssetModel) {
				// buttons based on image do not have outFrames
				outFrameKey = "null";
			} else {
				outFrameKey = frameKey((IAssetFrameModel) button.getAssetKey());
			}

			sb.append("button(" + // sprite
					round(button.getX())// x
					+ ", " + round(button.getY()) // y
					+ ", '" + button.getAssetKey().getAsset().getKey() + "'" // key
					+ ", " + emptyStringToNull(button.getCallback()) // callback
					+ ", " + emptyStringToNull(button.getCallbackContext()) // context
					+ ", " + frameKey(button.getOverFrame())// overFrame
					+ ", " + outFrameKey// outFrame
					+ ", " + frameKey(button.getDownFrame())// downFrame
					+ ", " + frameKey(button.getUpFrame())// upFrame
					+ ", " + parVar // group
					+ ")");
		} else if (model instanceof TileSpriteModel) {
			TileSpriteModel tile = (TileSpriteModel) model;
			sb.append("tileSprite(" + // sprite
					round(tile.getX())// x
					+ ", " + round(tile.getY()) // y
					+ ", " + round(tile.getWidth()) // width
					+ ", " + round(tile.getHeight()) // height
					+ ", '" + tile.getAssetKey().getAsset().getKey() + "'" // key
					+ ", '" + tile.getAssetKey().getKey() + "'"// frame
					+ ", " + parVar // group
					+ ")");
		}
		sb.append(";\n");

		// properties

		generateDisplayProps(indent, sb, model, parVar);

		generateSpriteProps(indent, sb, model, parVar);

		if (model instanceof TileSpriteModel) {
			generateTileProps(indent, sb, (TileSpriteModel) model, parVar);
		}
	}

	private static void generateDisplayProps(int indent, StringBuilder sb, BaseObjectModel model, String parVar) {
		String tabs = tabs(indent);
		String varname = parVar + "." + model.getEditorName();

		if (model instanceof GroupModel) {
			if (model.getX() != 0 || model.getY() != 0) {
				sb.append(tabs + varname + ".position.setTo(" + round(model.getX()) + ", " + round(model.getY())
						+ ");\n");
			}
		}

		if (model.getAngle() != 0) {
			sb.append(tabs + varname + ".angle = " + model.getAngle() + ";\n");
		}

		if (model.getScaleX() != 1 || model.getScaleY() != 1) {
			sb.append(tabs + varname + ".scale.setTo(" + model.getScaleX() + ", " + model.getScaleY() + ");\n");
		}

		if (model.getPivotX() != 0 || model.getPivotY() != 0) {
			sb.append(tabs + varname + ".pivot.setTo(" + model.getPivotX() + ", " + model.getPivotY() + ");\n");
		}
	}

	private static void generateSpriteProps(int indent, StringBuilder sb, BaseSpriteModel model, String parVar) {
		String tabs = tabs(indent);
		String varname = parVar + "." + model.getEditorName();

		if (model.getAnchorX() != 0 || model.getAnchorY() != 0) {
			sb.append(tabs + varname + ".anchor.setTo(" + model.getAnchorX() + ", " + model.getAnchorY() + ");\n");
		}

		if (model.getTint() != null && !model.getTint().equals("0xffffff")) {
			sb.append(tabs + varname + ".tint = " + model.getTint() + ";\n");
		}
	}

	private static void generateTileProps(int indent, StringBuilder sb, TileSpriteModel model, String parVar) {
		String tabs = tabs(indent);
		String varname = parVar + "." + model.getEditorName();

		if (model.getTilePositionX() != 0 || model.getTilePositionY() != 0) {
			sb.append(tabs + varname + ".tilePosition.setTo(" + round(model.getTilePositionX()) + ", "
					+ round(model.getTilePositionY()) + ");\n");
		}

		if (model.getTileScaleX() != 1 || model.getTileScaleY() != 1) {
			sb.append(tabs + varname + ".tileScale.setTo(" + model.getTileScaleX() + ", " + model.getTileScaleY()
					+ ");\n");
		}

	}

	private static void generateGroup(int indent, StringBuilder sb, GroupModel group, String parVar) {
		String tabs = tabs(indent);

		sb.append(tabs);
		sb.append(format("%s.%s = game.add.group(%s);\n", parVar, group.getEditorName(), parVar));

		generateDisplayProps(indent, sb, group, parVar);

		if (!group.getChildren().isEmpty()) {
			sb.append("\n");
			int i = 0;
			int last = group.getChildren().size() - 1;

			for (BaseObjectModel child : group.getChildren()) {
				generate(indent, sb, child, parVar + "." + group.getEditorName());
				if (i < last) {
					sb.append("\n");
				}
				i++;
			}
		}
	}

	private static String tabs(int indent) {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < indent; i++) {
			sb.append("\t");
		}
		return sb.toString();
	}

	private static String frameKey(IAssetFrameModel frame) {
		if (frame == null) {
			return "null";
		}

		if (frame instanceof SpritesheetAssetModel.FrameModel) {
			return Integer.toString(((SpritesheetAssetModel.FrameModel) frame).getIndex());
		}

		return "'" + frame.getKey() + "'";
	}

	private static String emptyStringToNull(String str) {
		return str == null ? null : (str.trim().length() == 0 ? null : str);
	}

	private static String round(double x) {
		return Integer.toString((int) Math.round(x));
	}
}
