// Generated by Phaser Editor v1.4.0 (Phaser v2.6.2)


/**
 * Menu.
 */
class Menu extends Phaser.State {
	
	constructor() {
		
		super();
		
	}
	
	init() {
		
	}
	
	preload () {
		
		this.load.pack('preloader', 'assets/pack.json');
		
	};
	
	create() {
		this.add.sprite(-172, -103, 'bg');
		
		this.add.sprite(285, 217, 'play');
		// user code
		this.initObjects();
		
	}
	
	
	/* state-methods-begin */
	
	initObjects() {
	
	}
	
	update() {
		if (this.input.activePointer.isDown) {
			this.game.state.start("Level");
		}
	}
	
	/* state-methods-end */
	
}
/* --- end generated code --- */
// -- user code here --
