// Generated by Phaser Editor v1.4.0 (Phaser v2.6.2)


/**
 * Coin.
 * @param aGame A reference to the currently running game.
 * @param aX The x coordinate (in world space) to position the Sprite at.
 * @param aY The y coordinate (in world space) to position the Sprite at.
 * @param aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
class Coin extends Phaser.Sprite {
	constructor(aGame : Phaser.Game, aX : number, aY : number, aKey? : any, aFrame? : any) {
		
		super(aGame, aX, aY, aKey === undefined? 'coins' : aKey, aFrame === undefined? 0 : aFrame);
		this.scale.setTo(0.5, 0.5);
		var _anim_rotate = this.animations.add('rotate', [0, 1, 2, 3, 4, 5], 5, true);
		
		// public fields
		
		this.fCoins = this;
		this.fAnim_rotate = _anim_rotate;
		
		// my code after objects creation
		this.afterCreate();
		
	}
	
	public fCoins : Phaser.Sprite;
	public fAnim_rotate : Phaser.Animation;
	
	/* sprite-methods-begin */
	
	afterCreate() {
		this.fAnim_rotate.play();
	}
	
	/* sprite-methods-end */
}
/* --- end generated code --- */
// -- user code here --
