// Generated by Phaser Editor v1.4.0 (Phaser v2.6.2)

/**
 * BaseEnemy.
 * 
 * @param {Phaser.Game}
 *            aGame A reference to the currently running game.
 * @param {Number}
 *            aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number}
 *            aY The y coordinate (in world space) to position the Sprite at.
 * @param {any}
 *            aKey This is the image or texture used by the Sprite during
 *            rendering. It can be a string which is a reference to the Cache
 *            entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any}
 *            aFrame If this Sprite is using part of a sprite sheet or texture
 *            atlas you can specify the exact frame to use by giving a string or
 *            numeric index.
 */
function BaseEnemy(aGame, aX, aY, aKey, aFrame) {

	var pKey = aKey === undefined ? null : aKey;
	var pFrame = aFrame === undefined ? null : aFrame;

	Phaser.Sprite.call(this, aGame, aX, aY, pKey, pFrame);

}

/** @type Phaser.Sprite */
var BaseEnemy_proto = Object.create(Phaser.Sprite.prototype);
BaseEnemy.prototype = BaseEnemy_proto;
BaseEnemy.prototype.constructor = BaseEnemy;

BaseEnemy.prototype.update = function() {

	// use the data set in the scene to move the enemies

	var data = this.data;
	
	if (data) {
		if (this.x < data.left) {
			this.body.velocity.x = 50;
		} else if (this.x > data.right) {
			this.body.velocity.x = -50;
		}

		if (this.body.velocity.x < 0) {
			this.scale.x = -1;
		} else if (this.body.velocity.x > 0) {
			this.scale.x = 1;
		}
	}
};
