// Generated by Phaser Editor v1.4.0 (Phaser v2.6.2)


/**
 * Level.
 */
class Level extends Phaser.State {
	
	constructor() {
		
		super();
		
	}
	
	init() {
		
		this.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
		this.scale.pageAlignHorizontally = true;
		this.scale.pageAlignVertically = true;
		this.stage.backgroundColor = '#ffffff';
		
	}
	
	preload () {
		
	};
	
	create() {
		// to change this code: Canvas editor > Configuration > Editor > userCode > Create
		this.addHelloWorldText();
		
		
	}
	
	
	/* state-methods-begin */
	
	addHelloWorldText() {
		this.add.text(100, 100, "hello world!", { fill : "#000" });
	}

	/* state-methods-end */
	
}
/* --- end generated code --- */
// -- user code here --
