
// -- user code here --

/* --- start generated code --- */

// Generated by Phaser Editor 1.4.3 (Phaser v2.6.2)


/**
 * Dino.
 * @param aGame A reference to the currently running game.
 * @param aX The x coordinate (in world space) to position the Sprite at.
 * @param aY The y coordinate (in world space) to position the Sprite at.
 * @param aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
class Dino extends Phaser.Sprite {
	constructor(aGame : Phaser.Game, aX : number, aY : number, aKey? : any, aFrame? : any) {
		
		super(aGame, aX, aY, aKey === undefined? 'dino' : aKey, aFrame === undefined? 1 : aFrame);
		var _anim_walk = this.animations.add('walk', [0, 1], 4, true);
		var _anim_stay = this.animations.add('stay', [0, 1, 2], 4, true);
		var _anim_jump = this.animations.add('jump', [4, 5], 4, true);
		_anim_stay.play();
		
		// public fields
		
		this.fAnim_walk = _anim_walk;
		this.fAnim_stay = _anim_stay;
		this.fAnim_jump = _anim_jump;
		
	}
	
	public fAnim_walk : Phaser.Animation;
	public fAnim_stay : Phaser.Animation;
	public fAnim_jump : Phaser.Animation;
	
	/* sprite-methods-begin */
	// -- user code here --
	/* sprite-methods-end */
}
/* --- end generated code --- */
// -- user code here --
